src/Feature Apex Trigger Assignment/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Session__c</fullName>
        <label>Training Session</label>
        <referenceTo>Training_Session__c</referenceTo>
        <relationshipLabel>Attendees (Training Session)</relationshipLabel>
        <relationshipName>Attendees1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Salutation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Feature Apex Trigger Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_Training_Session_Attended__c</fullName>
        <description>The no. of training session attended by attendee</description>
        <label>Total Training Session Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/Feature Apex Trigger Assignment/objects/Training_Session__c.object
<CustomObject>
    <label>Training Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Feature Apex Trigger Assignment/classes/AttendeeTriggerHandler.cls
/*
Description  : Manage All Events Related To Attendee.
Created By 	 : Akansha Dange
Created Date : 5-12-2024
*/
public virtual class AttendeeTriggerHandler extends TriggerHandler {
    // Implement the afterInsert method
    public override void afterInsert() {
        List<Attendee__c> newList=(List<Attendee__c>)Trigger.New;
        List<Attendee__c> oldList=(List<Attendee__c>)Trigger.Old;
        updateTotalTrainingSessions(newList, null);
    }

    // Implement the afterUpdate method
    public override void afterUpdate() {
        List<Attendee__c> newList=(List<Attendee__c>)Trigger.New;
        List<Attendee__c> oldList=(List<Attendee__c>)Trigger.Old;
        updateTotalTrainingSessions(newList,oldList);
    }

    // Implement the afterDelete method
    public override void afterDelete() {
        List<Attendee__c> newList=(List<Attendee__c>)Trigger.New;
        List<Attendee__c> oldList=(List<Attendee__c>)Trigger.Old;
        updateTotalTrainingSessions(null, oldList);
    }

    //update Total Training Sessions on the Contact record
    public static void updateTotalTrainingSessions(List<Attendee__c> newList, List<Attendee__c> oldList) {
        Set<Id> contactIdsToUpdate = new Set<Id>();
        if (newList != null) {
            for (Attendee__c attendee : newList) {
                if (attendee.Contact__c != null && attendee.Training_Session__c != null) {
                    contactIdsToUpdate.add(attendee.Contact__c);
                }
            }
        }
        if (oldList != null) {
            for (Attendee__c attendee : oldList) {
                if (attendee.Contact__c != null && attendee.Training_Session__c != null) {
                    contactIdsToUpdate.add(attendee.Contact__c);
                }
            }
        }
        if (contactIdsToUpdate.isEmpty()) {
            return;
        }
        Map<Id, Contact> contactsMap = new Map<Id, Contact>([SELECT Id, Total_Training_Session_Attended__c FROM Contact 
                                                             WHERE Id IN :contactIdsToUpdate]);
        List<AggregateResult> aggregateResults = [SELECT Contact__c, COUNT_DISTINCT(Training_Session__c) sessionCount 
                                                  FROM Attendee__c WHERE Contact__c IN :contactIdsToUpdate 
                                                  GROUP BY Contact__c];
        Map<Id, Integer> contactSessionCounts = new Map<Id, Integer>();
        for (AggregateResult result : aggregateResults) {
            Id contactId = (Id) result.get('Contact__c');
            Integer sessionCount = (Integer) result.get('sessionCount');
            contactSessionCounts.put(contactId, sessionCount);
        }
        List<Contact> contactsToUpdate = new List<Contact>();
        for (Id contactId : contactIdsToUpdate) {
            Contact contact = contactsMap.get(contactId);
            Integer sessionCount = contactSessionCounts.get(contactId);
            if (sessionCount != null) {
                contact.Total_Training_Session_Attended__c = sessionCount;
                contactsToUpdate.add(contact);
            }
        }
        if (!contactsToUpdate.isEmpty()) {
            update contactsToUpdate;
        }
    }
}